// copied from https://github.com/virgiling/virgiling.github.io/blob/v4/quartz/components/OutOfDate.tsx

import { QuartzComponent, QuartzComponentConstructor, QuartzComponentProps } from "./types"
import { classNames } from "../util/lang"

// NOTE This Component is generated by AI

interface OutOfDateConfig {
    /**
     * 需要检查过期的文件夹路径列表
     * 例如: ["/01-courses/", "/03-tools/"]
     */
    checkPaths?: string[]
    /**
     * 过期天数阈值，超过这个天数就会显示警告
     * 默认值: 60
     */
    staleThreshold?: number
}

export default ((config: OutOfDateConfig) => {
    const OutOfDate: QuartzComponent = ({ fileData, displayClass }: QuartzComponentProps) => {
        const checkPaths = config.checkPaths ?? ["/01-courses/", "/03-tools/"]
        const staleThreshold = config.staleThreshold ?? 60

        const filePath = fileData.filePath?.replace(/^content\//, "") || ""
        const isTargetPath = checkPaths.some(path => filePath.includes(path.replace(/^\//, "")))

        if (!isTargetPath) {
            return null
        }

        const frontmatterDate = fileData.frontmatter?.lastmod || fileData.frontmatter?.date
        const sysDate = fileData.dates?.modified || fileData.dates?.created
        const lastModified = frontmatterDate || sysDate

        if (!lastModified || typeof lastModified === 'object' && !('toString' in lastModified)) {
            return null
        }

        const currentDate = new Date()
        currentDate.setHours(0, 0, 0, 0)

        let modifiedDate: Date
        try {
            const dateValue = typeof lastModified === 'object' ? lastModified.toString() : String(lastModified)
            modifiedDate = new Date(dateValue)
            modifiedDate.setHours(0, 0, 0, 0)
            // 检查是否是有效日期
            if (isNaN(modifiedDate.getTime())) {
                return null
            }
        } catch {
            return null
        }

        const diffTime = currentDate.getTime() - modifiedDate.getTime()
        const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24))

        // 如果超过阈值天数，显示警告
        if (diffDays > staleThreshold) {
            return (
                <div class={classNames(displayClass, "callout")} data-callout="warning">
                    <div class="callout-title">
                        <div class="callout-icon"></div>
                        <div class="callout-title-inner">Warning</div>
                    </div>
                    <div class="callout-content">
                        <p>
                            本文最后更新已超过 {diffDays} 天。
                            内容可能已经过时，请注意参考时效性。
                        </p>
                    </div>
                </div>
            )
        }

        return null
    }

    return OutOfDate
}) satisfies QuartzComponentConstructor<OutOfDateConfig>